#!/usr/bin/env bash
# Install nginx on your web-01 server that listen on port 80

sudo apt update
sudo apt -y install nginx

echo "Hello World!" > /var/www/html/index.html

ufw allow 'Nginx HTTP'

service nginx restart
