#!/usr/bin/env bash
# Displays a string indefinitely and a specific string
# when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
