#!/usr/bin/env bash
# prints a string 10 times but displays a different
# string at the 9th iteration

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
