#!/usr/bin/env bash
# prints a string 10 times but displays a different
# string at the 4th and 8th iteration

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo $i
			echo "bad luck from China"
			;;
		9)
			echo $i
			echo "bad luck from Japan"
			;;
		17)
			echo $i
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac
	((i++))
done
