#!/usr/bin/env bash
#displays the time fpor 12 hrs 59 mins

hr=0
while [ $hr -le 12 ]
do
    echo "Hour: $hr";
    min=1;
    while [ $min -lt 60 ]
    do
        echo "$min";
        ((min++));
    done
    ((hr++))
done
